version: '3.8'

services:
  getcam:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app  # Adjust the volume path based on your project structure
    command: [ "poetry", "run", "python", "-m", "shot.shot", "run" ]
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: getcam_db
    ports:
      - "2612:5432"
    restart: unless-stopped
    volumes:
      - local_postgres_data_getcam:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 2

volumes:
  local_postgres_data_getcam:
