"""Init db

Revision ID: 3d769683b92b
Revises: 
Create Date: 2019-03-14 10:51:29.709006

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3d769683b92b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
                    sa.Column('admin_id', sa.Integer(), nullable=False),
                    sa.Column('chat_id', sa.BigInteger(), nullable=True),
                    sa.PrimaryKeyConstraint('admin_id'),
                    sa.UniqueConstraint('chat_id')
                    )
    op.create_table('channels',
                    sa.Column('channel_id', sa.Integer(), nullable=False),
                    sa.Column('chat_id', sa.BigInteger(), nullable=True),
                    sa.PrimaryKeyConstraint('channel_id'),
                    sa.UniqueConstraint('chat_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channels')
    op.drop_table('admins')
    # ### end Alembic commands ###
