"""add cam name to channel

Revision ID: bcf17df319b6
Revises: 3d769683b92b
Create Date: 2019-03-14 14:16:04.149231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf17df319b6'
down_revision = '3d769683b92b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('cam', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'cam')
    # ### end Alembic commands ###
