"""Add photo channel

Revision ID: 913dcf4adcd0
Revises: bcf17df319b6
Create Date: 2019-05-04 23:29:25.507812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913dcf4adcd0'
down_revision = 'bcf17df319b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_channels',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('cam', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('channel_id'),
    sa.UniqueConstraint('chat_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_channels')
    # ### end Alembic commands ###
