name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: DOCKER_BUILDKIT=1 BUILDKIT_PROGRESS=plain docker build . --file Dockerfile --target build --tag my-image-name:$(date +%s)
