name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: build
          tags: kiddten/getcam:latest
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: |
            type=registry,ref=kiddten/getcam:buildcache-amd64
            type=registry,ref=kiddten/getcam:buildcache-arm64
      - name: Cache amd64
        uses: docker/build-push-action@v5
        with:
          context: .
          target: build
          platforms: linux/amd64
          cache-from: type=registry,ref=kiddten/getcam:buildcache-amd64
          cache-to: type=registry,ref=kiddten/getcam:buildcache-amd64,mode=max
      - name: Cache arm64
        uses: docker/build-push-action@v5
        with:
          context: .
          target: build
          platforms: linux/arm64
          cache-from: type=registry,ref=kiddten/getcam:buildcache-arm64
          cache-to: type=registry,ref=kiddten/getcam:buildcache-arm64,mode=max
